# Site settings (accessible in Liquid templates via site.* variables)
title: "SDC Fall 2025 Team 17 Site"
description: >-
  An editable wiki powered by GitHub Pages
repository: rapidcow/site-wisc-sdc-fa25-team
url: https://rapidcow.github.io/site-wisc-sdc-fa25-team

src_name: "eyzmeng/site-wisc-sdc-fa25-team"
src_base: "https://github.com/eyzmeng/site-wisc-sdc-fa25-team"
src_head: "OUR"
src_root: "site/"

# https://github.com/pages-themes/minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
